export interface TerminoGlosario {
  id: string;
  termino: string;
  definicion: string;
  ejemplo: string;
  relacionados: string[];
  eje?: number;
}

export const GLOSARIO: TerminoGlosario[] = [
  // Eje 1: Talento y Capacidades
  {
    id: "t001",
    termino: "Oficial de Inteligencia Artificial (OIA)",
    definicion: "Responsable designado por la entidad para coordinar, supervisar e impulsar la gobernanza de IA en la organización, bajo los marcos de la ENIA 2026-2030.",
    ejemplo: "El OIA debe reportar directamente a la Alta Dirección y participar en mesas técnicas de la SGTD-PCM.",
    relacionados: ["Gobernanza de IA", "ENIA 2026-2030"],
    eje: 1,
  },
  {
    id: "t002",
    termino: "Talento Digital",
    definicion: "Programa de capacitación ofrecido por la Secretaría de Gobierno y Transformación Digital (SGTD-PCM) para formar funcionarios en habilidades digitales e IA.",
    ejemplo: "Los OIAs deben completar al menos un módulo de Talento Digital antes de junio de 2026.",
    relacionados: ["Capacitación en IA", "SGTD-PCM", "ENAP"],
    eje: 1,
  },
  {
    id: "t003",
    termino: "ENAP",
    definicion: "Escuela Nacional de Administración Pública (SERVIR) que ofrece formación especializada en Gobierno Digital e IA para el sector público.",
    ejemplo: "Módulo 'Inteligencia Artificial y Gobernanza Digital' es obligatorio para OIAs según la ENIA.",
    relacionados: ["Talento Digital", "SERVIR"],
    eje: 1,
  },
  {
    id: "t004",
    termino: "Capital Humano",
    definicion: "Conjunto de competencias, habilidades y conocimientos que posee una organización para innovar e implementar soluciones de IA.",
    ejemplo: "Una entidad con fuerte capital humano en IA puede reducir dependencia de proveedores externos.",
    relacionados: ["Talento Digital", "Competencias en IA"],
    eje: 1,
  },
  {
    id: "t005",
    termino: "Competencias en IA",
    definicion: "Conocimientos técnicos y transversales necesarios para desarrollar, implementar y gobernar sistemas de IA de forma ética y segura.",
    ejemplo: "Competencias incluyen: machine learning, ética algorítmica, gestión de riesgos de IA y cumplimiento normativo.",
    relacionados: ["Talento Digital", "Capital Humano"],
    eje: 1,
  },

  // Eje 2: Innovación y Emprendimiento
  {
    id: "i001",
    termino: "CNIDIA",
    definicion: "Centro Nacional de Innovación Digital e Inteligencia Artificial. Ecosistema que impulsa la innovación en IA para el sector público, privado y académico peruano.",
    ejemplo: "Las entidades pueden colaborar con CNIDIA para desarrollar pilotos de IA mediante incubación y mentorización.",
    relacionados: ["Innovación en IA", "Ecosistema Digital", "Emprendimiento"],
    eje: 2,
  },
  {
    id: "i002",
    termino: "datos.gob.pe",
    definicion: "Plataforma nacional de datos abiertos del gobierno peruano que facilita el acceso a datasets públicos para investigación e innovación en IA.",
    ejemplo: "Un emprendedor puede acceder a datos de salud pública de datos.gob.pe para entrenar modelos predictivos.",
    relacionados: ["Datos Abiertos", "Transparencia", "Innovación"],
    eje: 2,
  },
  {
    id: "i003",
    termino: "Datos Abiertos",
    definicion: "Conjuntos de datos públicos sin restricciones de acceso ni uso, disponibles en formato reutilizable (CSV, JSON, API) bajo licencia abierta.",
    ejemplo: "Datos sobre desempleo, educación y salud publicados en datos.gob.pe son datos abiertos que alimentan innovación.",
    relacionados: ["datos.gob.pe", "Transparencia", "Ecosistema Digital"],
    eje: 2,
  },
  {
    id: "i004",
    termino: "PROINNÓVATE",
    definicion: "Programa de inversión en innovación y emprendimiento de PRODUCE que financia proyectos de investigación y desarrollo en tecnologías emergentes como IA.",
    ejemplo: "Startups pueden postular a fondos PROINNÓVATE para desarrollar soluciones de IA en el sector agropecuario.",
    relacionados: ["Financiamiento", "Emprendimiento", "CONCYTEC"],
    eje: 2,
  },
  {
    id: "i005",
    termino: "CONCYTEC",
    definicion: "Consejo Nacional de Ciencia, Tecnología e Innovación Tecnológica que promueve investigación científica e innovación en tecnologías como IA.",
    ejemplo: "Investigadores pueden acceder a fondos CONCYTEC para proyectos de IA aplicada en soluciones públicas.",
    relacionados: ["Investigación", "Innovación", "PROINNÓVATE"],
    eje: 2,
  },
  {
    id: "i006",
    termino: "Piloto de IA",
    definicion: "Proyecto pequeño y controlado para probar la viabilidad de una solución de IA antes de su implementación a escala.",
    ejemplo: "Una municipalidad puede ejecutar un piloto de chatbot de IA para atención ciudadana antes de escalar a toda la entidad.",
    relacionados: ["Innovación en IA", "Implementación", "Gestión de Proyectos"],
    eje: 2,
  },
  {
    id: "i007",
    termino: "Ecosistema Digital",
    definicion: "Red integrada de actores (gobierno, empresas, academia, sociedad civil) que colaboran en el desarrollo e innovación de soluciones digitales e IA.",
    ejemplo: "El ecosistema digital peruano incluye CNIDIA, universidades, startups y organismos internacionales trabajando en IA.",
    relacionados: ["CNIDIA", "Innovación en IA", "Colaboración"],
    eje: 2,
  },

  // Eje 3: Marco Ético y Regulatorio
  {
    id: "e001",
    termino: "Gobernanza de IA",
    definicion: "Conjunto de políticas, procesos y estructuras que aseguran que los sistemas de IA se desarrollen e implementen de forma ética, segura, transparente y alineada con normas.",
    ejemplo: "La gobernanza de IA incluye: evaluaciones de impacto ético, supervisión humana significativa y mecanismos de rendición de cuentas.",
    relacionados: ["Ley N.° 31814", "Ética en IA", "Cumplimiento Normativo"],
    eje: 3,
  },
  {
    id: "e002",
    termino: "Ley N.° 31814",
    definicion: "Primera ley marco de Inteligencia Artificial en América Latina que regula el uso, desarrollo y gobernanza de sistemas de IA en el Perú.",
    ejemplo: "La Ley N.° 31814 exige que sistemas de IA de riesgo alto cuenten con supervisión humana significativa.",
    relacionados: ["Gobernanza de IA", "DS 115-2025-PCM", "Marco Regulatorio"],
    eje: 3,
  },
  {
    id: "e003",
    termino: "DS 115-2025-PCM",
    definicion: "Decreto Supremo que aprueba el Reglamento de la Ley N.° 31814, detallando obligaciones, plazos y procedimientos de implementación.",
    ejemplo: "DS 115-2025-PCM establece que entidades públicas deben implementar la NTP-ISO/IEC 42001:2025 antes de septiembre de 2026.",
    relacionados: ["Ley N.° 31814", "NTP-ISO/IEC 42001:2025", "Cumplimiento Normativo"],
    eje: 3,
  },
  {
    id: "e004",
    termino: "NTP-ISO/IEC 42001:2025",
    definicion: "Norma técnica peruana que establece requisitos para un Sistema de Gestión de Inteligencia Artificial (SGAI), incluyendo gobernanza, riesgos y conformidad.",
    ejemplo: "Las entidades públicas deben implementar la NTP-ISO/IEC 42001:2025 para certificar su sistema de gestión de IA.",
    relacionados: ["Gobernanza de IA", "Gestión de Riesgos de IA", "INACAL"],
    eje: 3,
  },
  {
    id: "e005",
    termino: "Evaluación de Impacto Ético (EIA-IA)",
    definicion: "Proceso de análisis previo al despliegue de un sistema de IA para identificar riesgos en términos de derechos humanos, discriminación, privacidad y transparencia.",
    ejemplo: "Antes de usar IA en decisiones de beneficios sociales, una entidad debe realizar una EIA-IA para evitar discriminación.",
    relacionados: ["Ética en IA", "Gestión de Riesgos de IA", "Derechos Humanos"],
    eje: 3,
  },
  {
    id: "e006",
    termino: "Supervisión Humana Significativa",
    definicion: "Participación activa, informada y en tiempo real de personas en la toma de decisiones críticas basadas en recomendaciones de sistemas de IA.",
    ejemplo: "En un sistema de IA para evaluación de créditos, un funcionario debe revisar y aprobar/rechazar cada decisión del modelo antes de ser ejecutada.",
    relacionados: ["Gobernanza de IA", "Ética en IA", "Derechos Humanos"],
    eje: 3,
  },
  {
    id: "e007",
    termino: "Gestión de Riesgos de IA",
    definicion: "Identificación, evaluación y mitigación de riesgos derivados del diseño, entrenamiento e implementación de sistemas de IA.",
    ejemplo: "Riesgos incluyen: sesgo algorítmico, privacidad de datos, falla de seguridad, y uso malicioso del sistema.",
    relacionados: ["Gobernanza de IA", "NTP-ISO/IEC 42001:2025", "Evaluación de Impacto Ético"],
    eje: 3,
  },
  {
    id: "e008",
    termino: "Transparencia Algorítmica",
    definicion: "Obligación de revelar información sobre cómo funciona un sistema de IA: datos de entrenamiento, criterios de decisión y limitaciones.",
    ejemplo: "Una agencia tributaria debe publicar documentación sobre cómo su sistema de IA detecta evasión fiscal.",
    relacionados: ["Gobernanza de IA", "Ética en IA", "Derechos Humanos"],
    eje: 3,
  },
  {
    id: "e009",
    termino: "Sesgo Algorítmico",
    definicion: "Error sistemático en un modelo de IA que favorece o perjudica desproporcionadamente a grupos específicos basado en características protegidas (género, edad, raza).",
    ejemplo: "Si un modelo de IA para contratación fue entrenado con datos históricos sesgados, perpetuará discriminación en género.",
    relacionados: ["Ética en IA", "Derechos Humanos", "Gestión de Riesgos de IA"],
    eje: 3,
  },
  {
    id: "e010",
    termino: "Derechos Humanos en IA",
    definicion: "Garantías fundamentales como privacidad, no discriminación, libertad de expresión y acceso a justicia en contextos donde se utiliza IA.",
    ejemplo: "Sistemas de vigilancia de IA no deben violar derecho a la privacidad; sistemas de calificación crediticia no deben discriminar.",
    relacionados: ["Ética en IA", "Gobernanza de IA", "Marco Regulatorio"],
    eje: 3,
  },

  // Eje 4: Participación y Colaboración
  {
    id: "c001",
    termino: "Participa Perú",
    definicion: "Plataforma digital de participación ciudadana del Estado peruano donde se consultan públicamente políticas, normas y decisiones públicas, incluyendo gobernanza de IA.",
    ejemplo: "Ciudadanos pueden opinar sobre borradores de regulación de IA en Participa Perú antes de su aprobación.",
    relacionados: ["Participación Ciudadana", "Transparencia", "ENIA 2026-2030"],
    eje: 4,
  },
  {
    id: "c002",
    termino: "Mesas Técnicas de Gobernanza de IA",
    definicion: "Espacios de diálogo multisectorial convocados por la SGTD-PCM donde actores (gobierno, empresa, academia, sociedad civil) definen políticas de IA.",
    ejemplo: "En una mesa técnica de SGTD, se discuten estándares de transparencia algorítmica aplicables a todas las entidades.",
    relacionados: ["Participación Ciudadana", "SGTD-PCM", "Colaboración"],
    eje: 4,
  },
  {
    id: "c003",
    termino: "SGTD-PCM",
    definicion: "Secretaría de Gobierno y Transformación Digital de la Presidencia del Consejo de Ministros. Ente rector de la ENIA 2026-2030 y responsable de gobernanza de IA nacional.",
    ejemplo: "SGTD-PCM aprueba Planes de Acción de entidades, coordina capacitación en IA y supervisa cumplimiento normativo.",
    relacionados: ["ENIA 2026-2030", "Gobernanza de IA", "Participación Ciudadana"],
    eje: 4,
  },
  {
    id: "c004",
    termino: "Alianzas Público-Privadas en IA",
    definicion: "Colaboraciones entre entidades públicas, empresas tecnológicas y universidades para desarrollar e implementar soluciones de IA que generen valor público.",
    ejemplo: "Una municipalidad se alía con una startup para co-desarrollar un sistema de optimización de recolección de residuos con IA.",
    relacionados: ["Colaboración", "Ecosistema Digital", "Innovación en IA"],
    eje: 4,
  },
  {
    id: "c005",
    termino: "Participación Ciudadana",
    definicion: "Involucramiento activo de ciudadanos y stakeholders en decisiones, diseño e implementación de políticas y sistemas de IA.",
    ejemplo: "Antes de desplegar un sistema de IA en servicios de salud, la entidad consulta a pacientes y trabajadores sanitarios.",
    relacionados: ["Participa Perú", "Gobernanza de IA", "Derechos Humanos"],
    eje: 4,
  },
  {
    id: "c006",
    termino: "Colaboración Internacional en IA",
    definicion: "Trabajo conjunto entre Perú y otros países/organismos internacionales (OCDE, UNESCO, APEC) en estándares, investigación y gobernanza de IA.",
    ejemplo: "Perú participa en grupos de trabajo de la OCDE sobre regulación de IA generativa.",
    relacionados: ["ENIA 2026-2030", "Participación Ciudadana", "Gobernanza de IA"],
    eje: 4,
  },

  // Términos Transversales
  {
    id: "x001",
    termino: "ENIA 2026-2030",
    definicion: "Estrategia Nacional de Inteligencia Artificial del Perú. Documento de política pública que define visión, objetivos y ejes para el desarrollo e implementación de IA en el país.",
    ejemplo: "La ENIA 2026-2030 tiene 4 ejes: Talento, Innovación, Marco Ético y Participación.",
    relacionados: ["SGTD-PCM", "Gobernanza de IA", "Plan de Acción ENIA"],
  },
  {
    id: "x002",
    termino: "Inteligencia Artificial",
    definicion: "Tecnología que permite a máquinas realizar tareas que normalmente requieren inteligencia humana, como aprendizaje, reconocimiento de patrones y toma de decisiones.",
    ejemplo: "Un chatbot que entiende y responde preguntas en lenguaje natural es una aplicación de IA generativa.",
    relacionados: ["Machine Learning", "IA Generativa", "Sistemas de IA"],
  },
  {
    id: "x003",
    termino: "Machine Learning",
    definicion: "Subcampo de IA donde algoritmos aprenden patrones de datos históricos sin ser explícitamente programados, mejorando su desempeño con más datos.",
    ejemplo: "Un modelo de machine learning para detectar fraude se entrena con transacciones históricas y mejora conforme procesa nuevas transacciones.",
    relacionados: ["Inteligencia Artificial", "Entrenamiento de Modelos", "Datos"],
  },
  {
    id: "x004",
    termino: "IA Generativa",
    definicion: "Sistemas de IA capaces de generar contenido nuevo (texto, imágenes, código) basado en patrones aprendidos de datos de entrenamiento.",
    ejemplo: "ChatGPT es un modelo de IA generativa que produce textos coherentes basado en prompts de usuarios.",
    relacionados: ["Inteligencia Artificial", "Large Language Models", "Transformers"],
  },
  {
    id: "x005",
    termino: "Ética en IA",
    definicion: "Conjunto de principios y prácticas que aseguran que sistemas de IA respeten valores como equidad, transparencia, privacidad y responsabilidad.",
    ejemplo: "La ética en IA exige que modelos de crédito no discriminen por género, raza o edad.",
    relacionados: ["Gobernanza de IA", "Derechos Humanos", "Regulación de IA"],
  },
  {
    id: "x006",
    termino: "Privacidad de Datos",
    definicion: "Derecho y práctica de proteger información personal de individuos contra acceso, uso o divulgación no autorizados.",
    ejemplo: "Un sistema de IA en salud debe encriptar datos de pacientes y garantizar que solo personal autorizado pueda acceder.",
    relacionados: ["Ética en IA", "Ley N.° 29733", "Seguridad de Datos"],
  },
  {
    id: "x007",
    termino: "Cumplimiento Normativo",
    definicion: "Adherencia de una organización a leyes, regulaciones y estándares aplicables a sus operaciones.",
    ejemplo: "Cumplimiento normativo en IA significa implementar NTP-ISO/IEC 42001:2025 y reportar avances a SGTD-PCM.",
    relacionados: ["Ley N.° 31814", "DS 115-2025-PCM", "Gobernanza de IA"],
  },
  {
    id: "x008",
    termino: "Entrenamiento de Modelos",
    definicion: "Proceso iterativo donde un algoritmo de aprendizaje ajusta sus parámetros usando datos de entrenamiento para minimizar errores.",
    ejemplo: "El entrenamiento de un modelo de clasificación de emails involucra miles de iteraciones ajustando pesos hasta lograr precisión.",
    relacionados: ["Machine Learning", "Datos", "Inteligencia Artificial"],
  },
  {
    id: "x009",
    termino: "Datos",
    definicion: "Información estructurada o no que es procesada, analizada y utilizada como insumo para entrenar e implementar sistemas de IA.",
    ejemplo: "Los datos sobre clima, geografía y cultivos entrenados en un modelo pueden predecir rendimiento agrícola.",
    relacionados: ["Entrenamiento de Modelos", "datos.gob.pe", "Privacidad de Datos"],
  },
];
